import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import SideBar from "./components/Sidebar";
import { Providers } from "./providers";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return(
    <html lang="ko">
      <body className="antialiased mx-auto w-full max-w-screen-md lg:max-w-screen-xl text-dark bg-white min-h-screen">
        <Providers>
          <Header />
          <Toaster position="top-center" />
          <div className="flex flex-col lg:flex-row w-full">
            <aside className="hidden lg:block lg:w-[220px] lg:flex-shrink-0">
              <SideBar />
            </aside>
            
            <main className="pt-[72px] flex-grow">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
